spring:
  application:
    name: "ServicioDiscos"

  datasource:
    url: jdbc:h2:file:c:/h2/bbdd_discos
    driverClassName: org.h2.Driver
    username: sa
    password: 
        
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect       